services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "strongpassword"
      N8N_HOST: "localhost"
      N8N_PORT: "5678"
      WEBHOOK_URL: "http://localhost:5678"
      GENERIC_TIMEZONE: "Asia/Kolkata"

      # Whitelist only these nodes:
      N8N_NODES_INCLUDE: "n8n-nodes-base.set,n8n-nodes-base.httpRequest,n8n-nodes-base.function"

      # (Optional) disable production main menu features
      N8N_DISABLE_PRODUCTION_MAIN_MENU: "true"

    volumes:
      - n8n_data:/home/node/.n8n
      - ./custom-nodes:/home/node/.n8n/custom

volumes:
  n8n_data:
